project_id = "hztymrdzeehidydtkfpp"

[functions.extract-content]
verify_jwt = false

[functions.evaluate-answer]
verify_jwt = false

[functions.check-gap-fill]
verify_jwt = false

[functions.generate-mock-exam]
verify_jwt = false

[functions.mark-mock-exam]
verify_jwt = false

[functions.rewrite-exam-sentence]
verify_jwt = false

[functions.planning-assistant]
verify_jwt = false
